find_path(SQLITE_INCLUDE_DIRS sqlite3.h)

find_library(SQLITE_LIBRARIES NAMES libsqlite3 sqlite3)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(SQLite DEFAULT_MSG SQLITE_LIBRARIES SQLITE_INCLUDE_DIRS)
mark_as_advanced(SQLITE_INCLUDE_DIRS SQLITE_LIBRARIES)
