<?php
namespace chronos;

/**
 * Autogenerated by Thrift Compiler (0.18.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class ChronosNode_submitJobTestRun_args
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'job',
            'isRequired' => false,
            'type' => TType::STRUCT,
            'class' => '\chronos\Job',
        ),
        2 => array(
            'var' => 'xForwardedFor',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
    );

    /**
     * @var \chronos\Job
     */
    public $job = null;
    /**
     * @var string
     */
    public $xForwardedFor = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['job'])) {
                $this->job = $vals['job'];
            }
            if (isset($vals['xForwardedFor'])) {
                $this->xForwardedFor = $vals['xForwardedFor'];
            }
        }
    }

    public function getName()
    {
        return 'ChronosNode_submitJobTestRun_args';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::STRUCT) {
                        $this->job = new \chronos\Job();
                        $xfer += $this->job->read($input);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->xForwardedFor);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('ChronosNode_submitJobTestRun_args');
        if ($this->job !== null) {
            if (!is_object($this->job)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('job', TType::STRUCT, 1);
            $xfer += $this->job->write($output);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->xForwardedFor !== null) {
            $xfer += $output->writeFieldBegin('xForwardedFor', TType::STRING, 2);
            $xfer += $output->writeString($this->xForwardedFor);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
