<?php
namespace chronos;

/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class JobExecutionInfo
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'lastStatus',
            'isRequired' => false,
            'type' => TType::I32,
        ),
        2 => array(
            'var' => 'lastFetch',
            'isRequired' => false,
            'type' => TType::I64,
        ),
        3 => array(
            'var' => 'lastDuration',
            'isRequired' => false,
            'type' => TType::I32,
        ),
        4 => array(
            'var' => 'failCounter',
            'isRequired' => false,
            'type' => TType::I32,
        ),
    );

    /**
     * @var int
     */
    public $lastStatus = null;
    /**
     * @var int
     */
    public $lastFetch = null;
    /**
     * @var int
     */
    public $lastDuration = null;
    /**
     * @var int
     */
    public $failCounter = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['lastStatus'])) {
                $this->lastStatus = $vals['lastStatus'];
            }
            if (isset($vals['lastFetch'])) {
                $this->lastFetch = $vals['lastFetch'];
            }
            if (isset($vals['lastDuration'])) {
                $this->lastDuration = $vals['lastDuration'];
            }
            if (isset($vals['failCounter'])) {
                $this->failCounter = $vals['failCounter'];
            }
        }
    }

    public function getName()
    {
        return 'JobExecutionInfo';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::I32) {
                        $xfer += $input->readI32($this->lastStatus);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::I64) {
                        $xfer += $input->readI64($this->lastFetch);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 3:
                    if ($ftype == TType::I32) {
                        $xfer += $input->readI32($this->lastDuration);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 4:
                    if ($ftype == TType::I32) {
                        $xfer += $input->readI32($this->failCounter);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('JobExecutionInfo');
        if ($this->lastStatus !== null) {
            $xfer += $output->writeFieldBegin('lastStatus', TType::I32, 1);
            $xfer += $output->writeI32($this->lastStatus);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->lastFetch !== null) {
            $xfer += $output->writeFieldBegin('lastFetch', TType::I64, 2);
            $xfer += $output->writeI64($this->lastFetch);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->lastDuration !== null) {
            $xfer += $output->writeFieldBegin('lastDuration', TType::I32, 3);
            $xfer += $output->writeI32($this->lastDuration);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->failCounter !== null) {
            $xfer += $output->writeFieldBegin('failCounter', TType::I32, 4);
            $xfer += $output->writeI32($this->failCounter);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
