<?php
namespace chronos;

/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class JobNotification
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'onFailure',
            'isRequired' => false,
            'type' => TType::BOOL,
        ),
        2 => array(
            'var' => 'onSuccess',
            'isRequired' => false,
            'type' => TType::BOOL,
        ),
        3 => array(
            'var' => 'onDisable',
            'isRequired' => false,
            'type' => TType::BOOL,
        ),
    );

    /**
     * @var bool
     */
    public $onFailure = null;
    /**
     * @var bool
     */
    public $onSuccess = null;
    /**
     * @var bool
     */
    public $onDisable = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['onFailure'])) {
                $this->onFailure = $vals['onFailure'];
            }
            if (isset($vals['onSuccess'])) {
                $this->onSuccess = $vals['onSuccess'];
            }
            if (isset($vals['onDisable'])) {
                $this->onDisable = $vals['onDisable'];
            }
        }
    }

    public function getName()
    {
        return 'JobNotification';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::BOOL) {
                        $xfer += $input->readBool($this->onFailure);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::BOOL) {
                        $xfer += $input->readBool($this->onSuccess);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 3:
                    if ($ftype == TType::BOOL) {
                        $xfer += $input->readBool($this->onDisable);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('JobNotification');
        if ($this->onFailure !== null) {
            $xfer += $output->writeFieldBegin('onFailure', TType::BOOL, 1);
            $xfer += $output->writeBool($this->onFailure);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->onSuccess !== null) {
            $xfer += $output->writeFieldBegin('onSuccess', TType::BOOL, 2);
            $xfer += $output->writeBool($this->onSuccess);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->onDisable !== null) {
            $xfer += $output->writeFieldBegin('onDisable', TType::BOOL, 3);
            $xfer += $output->writeBool($this->onDisable);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
