<?php
namespace chronos;

/**
 * Autogenerated by Thrift Compiler (0.23.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class JobNotification
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'onFailure',
            'isRequired' => false,
            'type' => TType::BOOL,
        ),
        2 => array(
            'var' => 'onSuccess',
            'isRequired' => false,
            'type' => TType::BOOL,
        ),
        3 => array(
            'var' => 'onDisable',
            'isRequired' => false,
            'type' => TType::BOOL,
        ),
        4 => array(
            'var' => 'onFailureCount',
            'isRequired' => false,
            'type' => TType::I32,
        ),
        5 => array(
            'var' => 'onSslCertExpiry',
            'isRequired' => false,
            'type' => TType::BOOL,
        ),
        6 => array(
            'var' => 'onSslCertExpirySeconds',
            'isRequired' => false,
            'type' => TType::I32,
        ),
        7 => array(
            'var' => 'mode',
            'isRequired' => false,
            'type' => TType::I32,
            'class' => '\chronos\JobNotificationMode',
        ),
        8 => array(
            'var' => 'selectedChannels',
            'isRequired' => false,
            'type' => TType::LST,
            'etype' => TType::I64,
            'elem' => array(
                'type' => TType::I64,
            ),
        ),
    );

    /**
     * @var bool
     */
    public $onFailure = null;
    /**
     * @var bool
     */
    public $onSuccess = null;
    /**
     * @var bool
     */
    public $onDisable = null;
    /**
     * @var int
     */
    public $onFailureCount = null;
    /**
     * @var bool
     */
    public $onSslCertExpiry = null;
    /**
     * @var int
     */
    public $onSslCertExpirySeconds = null;
    /**
     * @var int
     */
    public $mode = null;
    /**
     * @var int[]
     */
    public $selectedChannels = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['onFailure'])) {
                $this->onFailure = $vals['onFailure'];
            }
            if (isset($vals['onSuccess'])) {
                $this->onSuccess = $vals['onSuccess'];
            }
            if (isset($vals['onDisable'])) {
                $this->onDisable = $vals['onDisable'];
            }
            if (isset($vals['onFailureCount'])) {
                $this->onFailureCount = $vals['onFailureCount'];
            }
            if (isset($vals['onSslCertExpiry'])) {
                $this->onSslCertExpiry = $vals['onSslCertExpiry'];
            }
            if (isset($vals['onSslCertExpirySeconds'])) {
                $this->onSslCertExpirySeconds = $vals['onSslCertExpirySeconds'];
            }
            if (isset($vals['mode'])) {
                $this->mode = $vals['mode'];
            }
            if (isset($vals['selectedChannels'])) {
                $this->selectedChannels = $vals['selectedChannels'];
            }
        }
    }

    public function getName()
    {
        return 'JobNotification';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::BOOL) {
                        $xfer += $input->readBool($this->onFailure);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::BOOL) {
                        $xfer += $input->readBool($this->onSuccess);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 3:
                    if ($ftype == TType::BOOL) {
                        $xfer += $input->readBool($this->onDisable);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 4:
                    if ($ftype == TType::I32) {
                        $xfer += $input->readI32($this->onFailureCount);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 5:
                    if ($ftype == TType::BOOL) {
                        $xfer += $input->readBool($this->onSslCertExpiry);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 6:
                    if ($ftype == TType::I32) {
                        $xfer += $input->readI32($this->onSslCertExpirySeconds);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 7:
                    if ($ftype == TType::I32) {
                        $xfer += $input->readI32($this->mode);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 8:
                    if ($ftype == TType::LST) {
                        $this->selectedChannels = array();
                        $_size = 0;
                        $_etype = 0;
                        $xfer += $input->readListBegin($_etype, $_size);
                        for ($_i = 0; $_i < $_size; ++$_i) {
                            $elem = null;
                            $xfer += $input->readI64($elem);
                            $this->selectedChannels[] = $elem;
                        }
                        $xfer += $input->readListEnd();
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('JobNotification');
        if ($this->onFailure !== null) {
            $xfer += $output->writeFieldBegin('onFailure', TType::BOOL, 1);
            $xfer += $output->writeBool($this->onFailure);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->onSuccess !== null) {
            $xfer += $output->writeFieldBegin('onSuccess', TType::BOOL, 2);
            $xfer += $output->writeBool($this->onSuccess);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->onDisable !== null) {
            $xfer += $output->writeFieldBegin('onDisable', TType::BOOL, 3);
            $xfer += $output->writeBool($this->onDisable);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->onFailureCount !== null) {
            $xfer += $output->writeFieldBegin('onFailureCount', TType::I32, 4);
            $xfer += $output->writeI32($this->onFailureCount);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->onSslCertExpiry !== null) {
            $xfer += $output->writeFieldBegin('onSslCertExpiry', TType::BOOL, 5);
            $xfer += $output->writeBool($this->onSslCertExpiry);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->onSslCertExpirySeconds !== null) {
            $xfer += $output->writeFieldBegin('onSslCertExpirySeconds', TType::I32, 6);
            $xfer += $output->writeI32($this->onSslCertExpirySeconds);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->mode !== null) {
            $xfer += $output->writeFieldBegin('mode', TType::I32, 7);
            $xfer += $output->writeI32($this->mode);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->selectedChannels !== null) {
            $xfer += $output->writeFieldBegin('selectedChannels', TType::LST, 8);
            $output->writeListBegin(TType::I64, count($this->selectedChannels));
            foreach ($this->selectedChannels as $iter) {
                $xfer += $output->writeI64($iter);
            }
            $output->writeListEnd();
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
