<?php
namespace chronos;

/**
 * Autogenerated by Thrift Compiler (0.23.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

final class JobNotificationMode
{
    const NONE = 0;

    const ALL = 1;

    const SELECTED = 2;

    static public $__names = array(
        0 => 'NONE',
        1 => 'ALL',
        2 => 'SELECTED',
    );
}
