<?php
namespace chronos;

/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

final class JobStatus
{
    const UNKNOWN = 0;

    const OK = 1;

    const FAILED_DNS = 2;

    const FAILED_CONNECT = 3;

    const FAILED_HTTPERROR = 4;

    const FAILED_TIMEOUT = 5;

    const FAILED_SIZE = 6;

    const FAILED_URL = 7;

    const FAILED_INTERNAL = 8;

    const FAILED_OTHERS = 9;

    static public $__names = array(
        0 => 'UNKNOWN',
        1 => 'OK',
        2 => 'FAILED_DNS',
        3 => 'FAILED_CONNECT',
        4 => 'FAILED_HTTPERROR',
        5 => 'FAILED_TIMEOUT',
        6 => 'FAILED_SIZE',
        7 => 'FAILED_URL',
        8 => 'FAILED_INTERNAL',
        9 => 'FAILED_OTHERS',
    );
}

