<?php
namespace chronos;

/**
 * Autogenerated by Thrift Compiler (0.23.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class NotificationChannel
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'channelId',
            'isRequired' => false,
            'type' => TType::I64,
        ),
        2 => array(
            'var' => 'type',
            'isRequired' => false,
            'type' => TType::I32,
            'class' => '\chronos\NotificationChannelType',
        ),
        3 => array(
            'var' => 'destination',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        4 => array(
            'var' => 'enabled',
            'isRequired' => false,
            'type' => TType::BOOL,
        ),
        5 => array(
            'var' => 'settings',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
    );

    /**
     * @var int
     */
    public $channelId = null;
    /**
     * @var int
     */
    public $type = null;
    /**
     * @var string
     */
    public $destination = null;
    /**
     * @var bool
     */
    public $enabled = null;
    /**
     * @var string
     */
    public $settings = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['channelId'])) {
                $this->channelId = $vals['channelId'];
            }
            if (isset($vals['type'])) {
                $this->type = $vals['type'];
            }
            if (isset($vals['destination'])) {
                $this->destination = $vals['destination'];
            }
            if (isset($vals['enabled'])) {
                $this->enabled = $vals['enabled'];
            }
            if (isset($vals['settings'])) {
                $this->settings = $vals['settings'];
            }
        }
    }

    public function getName()
    {
        return 'NotificationChannel';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::I64) {
                        $xfer += $input->readI64($this->channelId);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::I32) {
                        $xfer += $input->readI32($this->type);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 3:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->destination);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 4:
                    if ($ftype == TType::BOOL) {
                        $xfer += $input->readBool($this->enabled);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 5:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->settings);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('NotificationChannel');
        if ($this->channelId !== null) {
            $xfer += $output->writeFieldBegin('channelId', TType::I64, 1);
            $xfer += $output->writeI64($this->channelId);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->type !== null) {
            $xfer += $output->writeFieldBegin('type', TType::I32, 2);
            $xfer += $output->writeI32($this->type);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->destination !== null) {
            $xfer += $output->writeFieldBegin('destination', TType::STRING, 3);
            $xfer += $output->writeString($this->destination);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->enabled !== null) {
            $xfer += $output->writeFieldBegin('enabled', TType::BOOL, 4);
            $xfer += $output->writeBool($this->enabled);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->settings !== null) {
            $xfer += $output->writeFieldBegin('settings', TType::STRING, 5);
            $xfer += $output->writeString($this->settings);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
