<?php
namespace chronos;

/**
 * Autogenerated by Thrift Compiler (0.23.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

final class NotificationResult
{
    const SUCCESS = 0;

    const FAILED_PREPROCESS = 1;

    const FAILED_SEND = 2;

    const FAILED_OTHERS = 3;

    static public $__names = array(
        0 => 'SUCCESS',
        1 => 'FAILED_PREPROCESS',
        2 => 'FAILED_SEND',
        3 => 'FAILED_OTHERS',
    );
}

