<?php
namespace chronos;

/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class Phrases
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'phrases',
            'isRequired' => false,
            'type' => TType::MAP,
            'ktype' => TType::STRING,
            'vtype' => TType::MAP,
            'key' => array(
                'type' => TType::STRING,
            ),
            'val' => array(
                'type' => TType::MAP,
                'ktype' => TType::STRING,
                'vtype' => TType::STRING,
                'key' => array(
                    'type' => TType::STRING,
                ),
                'val' => array(
                    'type' => TType::STRING,
                    ),
                ),
        ),
    );

    /**
     * @var array
     */
    public $phrases = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['phrases'])) {
                $this->phrases = $vals['phrases'];
            }
        }
    }

    public function getName()
    {
        return 'Phrases';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::MAP) {
                        $this->phrases = array();
                        $_size49 = 0;
                        $_ktype50 = 0;
                        $_vtype51 = 0;
                        $xfer += $input->readMapBegin($_ktype50, $_vtype51, $_size49);
                        for ($_i53 = 0; $_i53 < $_size49; ++$_i53) {
                            $key54 = '';
                            $val55 = array();
                            $xfer += $input->readString($key54);
                            $val55 = array();
                            $_size56 = 0;
                            $_ktype57 = 0;
                            $_vtype58 = 0;
                            $xfer += $input->readMapBegin($_ktype57, $_vtype58, $_size56);
                            for ($_i60 = 0; $_i60 < $_size56; ++$_i60) {
                                $key61 = '';
                                $val62 = '';
                                $xfer += $input->readString($key61);
                                $xfer += $input->readString($val62);
                                $val55[$key61] = $val62;
                            }
                            $xfer += $input->readMapEnd();
                            $this->phrases[$key54] = $val55;
                        }
                        $xfer += $input->readMapEnd();
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('Phrases');
        if ($this->phrases !== null) {
            if (!is_array($this->phrases)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('phrases', TType::MAP, 1);
            $output->writeMapBegin(TType::STRING, TType::MAP, count($this->phrases));
            foreach ($this->phrases as $kiter63 => $viter64) {
                $xfer += $output->writeString($kiter63);
                $output->writeMapBegin(TType::STRING, TType::STRING, count($viter64));
                foreach ($viter64 as $kiter65 => $viter66) {
                    $xfer += $output->writeString($kiter65);
                    $xfer += $output->writeString($viter66);
                }
                $output->writeMapEnd();
            }
            $output->writeMapEnd();
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
