<?php
namespace chronos;

/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class TimeSeriesDataEntry
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'date',
            'isRequired' => false,
            'type' => TType::I64,
        ),
        2 => array(
            'var' => 'duration',
            'isRequired' => false,
            'type' => TType::I32,
        ),
        3 => array(
            'var' => 'uptimeCounter',
            'isRequired' => false,
            'type' => TType::I32,
        ),
        4 => array(
            'var' => 'uptimeDenominator',
            'isRequired' => false,
            'type' => TType::I32,
        ),
    );

    /**
     * @var int
     */
    public $date = null;
    /**
     * @var int
     */
    public $duration = null;
    /**
     * @var int
     */
    public $uptimeCounter = null;
    /**
     * @var int
     */
    public $uptimeDenominator = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['date'])) {
                $this->date = $vals['date'];
            }
            if (isset($vals['duration'])) {
                $this->duration = $vals['duration'];
            }
            if (isset($vals['uptimeCounter'])) {
                $this->uptimeCounter = $vals['uptimeCounter'];
            }
            if (isset($vals['uptimeDenominator'])) {
                $this->uptimeDenominator = $vals['uptimeDenominator'];
            }
        }
    }

    public function getName()
    {
        return 'TimeSeriesDataEntry';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::I64) {
                        $xfer += $input->readI64($this->date);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::I32) {
                        $xfer += $input->readI32($this->duration);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 3:
                    if ($ftype == TType::I32) {
                        $xfer += $input->readI32($this->uptimeCounter);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 4:
                    if ($ftype == TType::I32) {
                        $xfer += $input->readI32($this->uptimeDenominator);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('TimeSeriesDataEntry');
        if ($this->date !== null) {
            $xfer += $output->writeFieldBegin('date', TType::I64, 1);
            $xfer += $output->writeI64($this->date);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->duration !== null) {
            $xfer += $output->writeFieldBegin('duration', TType::I32, 2);
            $xfer += $output->writeI32($this->duration);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->uptimeCounter !== null) {
            $xfer += $output->writeFieldBegin('uptimeCounter', TType::I32, 3);
            $xfer += $output->writeI32($this->uptimeCounter);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->uptimeDenominator !== null) {
            $xfer += $output->writeFieldBegin('uptimeDenominator', TType::I32, 4);
            $xfer += $output->writeI32($this->uptimeDenominator);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
