<?php
namespace chronos;

/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class TimeSeriesData
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'last24Hours',
            'isRequired' => false,
            'type' => TType::LST,
            'etype' => TType::STRUCT,
            'elem' => array(
                'type' => TType::STRUCT,
                'class' => '\chronos\TimeSeriesDataEntry',
                ),
        ),
        2 => array(
            'var' => 'last12Months',
            'isRequired' => false,
            'type' => TType::LST,
            'etype' => TType::STRUCT,
            'elem' => array(
                'type' => TType::STRUCT,
                'class' => '\chronos\TimeSeriesDataEntry',
                ),
        ),
    );

    /**
     * @var \chronos\TimeSeriesDataEntry[]
     */
    public $last24Hours = null;
    /**
     * @var \chronos\TimeSeriesDataEntry[]
     */
    public $last12Months = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['last24Hours'])) {
                $this->last24Hours = $vals['last24Hours'];
            }
            if (isset($vals['last12Months'])) {
                $this->last12Months = $vals['last12Months'];
            }
        }
    }

    public function getName()
    {
        return 'TimeSeriesData';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::LST) {
                        $this->last24Hours = array();
                        $_size67 = 0;
                        $_etype70 = 0;
                        $xfer += $input->readListBegin($_etype70, $_size67);
                        for ($_i71 = 0; $_i71 < $_size67; ++$_i71) {
                            $elem72 = null;
                            $elem72 = new \chronos\TimeSeriesDataEntry();
                            $xfer += $elem72->read($input);
                            $this->last24Hours []= $elem72;
                        }
                        $xfer += $input->readListEnd();
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::LST) {
                        $this->last12Months = array();
                        $_size73 = 0;
                        $_etype76 = 0;
                        $xfer += $input->readListBegin($_etype76, $_size73);
                        for ($_i77 = 0; $_i77 < $_size73; ++$_i77) {
                            $elem78 = null;
                            $elem78 = new \chronos\TimeSeriesDataEntry();
                            $xfer += $elem78->read($input);
                            $this->last12Months []= $elem78;
                        }
                        $xfer += $input->readListEnd();
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('TimeSeriesData');
        if ($this->last24Hours !== null) {
            if (!is_array($this->last24Hours)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('last24Hours', TType::LST, 1);
            $output->writeListBegin(TType::STRUCT, count($this->last24Hours));
            foreach ($this->last24Hours as $iter79) {
                $xfer += $iter79->write($output);
            }
            $output->writeListEnd();
            $xfer += $output->writeFieldEnd();
        }
        if ($this->last12Months !== null) {
            if (!is_array($this->last12Months)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('last12Months', TType::LST, 2);
            $output->writeListBegin(TType::STRUCT, count($this->last12Months));
            foreach ($this->last12Months as $iter80) {
                $xfer += $iter80->write($output);
            }
            $output->writeListEnd();
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
