<?php
namespace chronos;

/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class WAFValidatorResult
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'blocked',
            'isRequired' => false,
            'type' => TType::BOOL,
        ),
        2 => array(
            'var' => 'status',
            'isRequired' => false,
            'type' => TType::I16,
        ),
        3 => array(
            'var' => 'log',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        4 => array(
            'var' => 'additionalLogs',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
    );

    /**
     * @var bool
     */
    public $blocked = null;
    /**
     * @var int
     */
    public $status = null;
    /**
     * @var string
     */
    public $log = null;
    /**
     * @var string
     */
    public $additionalLogs = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['blocked'])) {
                $this->blocked = $vals['blocked'];
            }
            if (isset($vals['status'])) {
                $this->status = $vals['status'];
            }
            if (isset($vals['log'])) {
                $this->log = $vals['log'];
            }
            if (isset($vals['additionalLogs'])) {
                $this->additionalLogs = $vals['additionalLogs'];
            }
        }
    }

    public function getName()
    {
        return 'WAFValidatorResult';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::BOOL) {
                        $xfer += $input->readBool($this->blocked);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::I16) {
                        $xfer += $input->readI16($this->status);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 3:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->log);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 4:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->additionalLogs);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('WAFValidatorResult');
        if ($this->blocked !== null) {
            $xfer += $output->writeFieldBegin('blocked', TType::BOOL, 1);
            $xfer += $output->writeBool($this->blocked);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->status !== null) {
            $xfer += $output->writeFieldBegin('status', TType::I16, 2);
            $xfer += $output->writeI16($this->status);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->log !== null) {
            $xfer += $output->writeFieldBegin('log', TType::STRING, 3);
            $xfer += $output->writeString($this->log);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->additionalLogs !== null) {
            $xfer += $output->writeFieldBegin('additionalLogs', TType::STRING, 4);
            $xfer += $output->writeString($this->additionalLogs);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
