# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build Frontend

on:
  push:
    branches: [ prod, actions-test ]

jobs:
  build-frontend:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ./frontend/package-lock.json
    - run: 'echo "$FRONTEND_CONFIG" > ./src/utils/Config.js'
      shell: bash
      env:
        FRONTEND_CONFIG: ${{secrets.FRONTEND_CONFIG}}
      working-directory: ./frontend
    - run: npm ci
      working-directory: ./frontend
    - run: npm run build --if-present
      working-directory: ./frontend
    - name: 'Upload new assets to s3'
      uses: chrislennon/action-aws-cli@v1.1
    - run: aws s3 sync ./build s3://$FRONTEND_S3_BUCKET_NAME --exclude "*.map"
      working-directory: ./frontend
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        FRONTEND_S3_BUCKET_NAME: ${{ secrets.FRONTEND_S3_BUCKET_NAME }}
